config/routes.rb
Rails.application.routes.draw do
  root to: "dashboards#show"

  resources :events, only: [:create]
  resource :dashboard, only: [:create, :show]
  resource :data_request, only: [:create]
  resource :real_time_events, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard_data_presenter.rb
class DashboardDataPresenter
  attr_reader :start_date, :end_date

  def initialize(start_date:, end_date:)
    @start_date = start_date || DateTime.current.beginning_of_year
    @end_date = end_date || DateTime.current
  end

  def sent(type: all_email_types)
    event_count(type: type, event: "send")
  end

  def opened(type: all_email_types)
    event_count(type: type, event: "open")
  end

  def clicked(type: all_email_types)
    event_count(type: type, event: "click")
  end

  def open_rate(type: all_email_types)
    percentage_rate(
      numerator: sent(type: type),
      denominator: opened(type: type)
    )
  end

  def click_rate(type: all_email_types)
    percentage_rate(
      numerator: opened(type: type),
      denominator: clicked(type: type)
    )
  end

  def all_email_types
    @_all_email_types || Event.pluck(:email_type).uniq
  end

  private

  def event_count(type: all_email_types, event:)
    Event.where(event: event)
      .where(email_type: type)
      .where("created_at > ?", start_date)
      .where("created_at < ?", end_date)
      .count
  end

  def percentage_rate(numerator:, denominator:)
    begin
      ((100/numerator.to_f)*denominator.to_f).round(2)
    rescue
      0
    end
  end
end

app/models/data_miner.rb
class DataMiner
  def initialize(start_date:, end_date:)
    @start_date = start_date
    @end_date = end_date
  end

  def show_conversion_rates?
    sent > 0
  end

  def last_ten_events
    Event
      .order_by_timestamp
      .last(10)
  end

  def sent(type: all_email_types)
    Rails.cache.fetch("sent_#{type}_#{start_date}_#{end_date}", expires_in: cache_expire_time) do
      event_count(type: type, event: "send")
    end
  end

  def opened(type: all_email_types)
    Rails.cache.fetch("opened_#{type}_#{start_date}_#{end_date}", expires_in: cache_expire_time) do
      event_count(type: type, event: "open")
    end
  end

  def clicked(type: all_email_types)
    Rails.cache.fetch("clicked_#{type}_#{start_date}_#{end_date}", expires_in: cache_expire_time) do
      event_count(type: type, event: "click")
    end
  end

  def open_rate(type: all_email_types)
    Rails.cache.fetch("open_rate_#{type}_#{start_date}_#{end_date}", expires_in: cache_expire_time) do
      percentage_rate(
        numerator: sent(type: type),
        denominator: opened(type: type)
      )
    end
  end

  def click_rate(type: all_email_types)
    Rails.cache.fetch("click_rate_#{type}_#{start_date}_#{end_date}", expires_in: cache_expire_time) do
      percentage_rate(
        numerator: sent(type: type),
        denominator: clicked(type: type)
      )
    end
  end

  def all_email_types
    @_all_email_types ||= Rails.cache.fetch("email_types", expires_in: 12.hours) do
      Event.pluck(:email_type).uniq
    end
  end

  private

  def cache_expire_time
    if end_date == Date.today
      1.hour
    else
      2.weeks
    end
  end

  def start_date
    DateTime.parse(@start_date.to_s)
  end

  def end_date
    DateTime.parse(@end_date.to_s)
  end

  def event_count(type: all_email_types, event:)
    Event.where(event: event)
      .where(email_type: type)
      .where("timestamp > ?", start_date)
      .where("timestamp < ?", end_date)
      .count
  end

  def percentage_rate(numerator:, denominator:)
    ((100/numerator.to_f)*denominator.to_f).round(2)
  end
end

app/models/data_request.rb
class DataRequest < ActiveResource::Base
  self.site = ENV.fetch("DUMMY_EVENTS_URL")
end

app/models/event.rb
class Event < ApplicationRecord
  validates :address, presence: true
  validates :email_type, presence: true
  validates :event, presence: true
  validates :timestamp, presence: true

  after_create :notify_real_time_feed

  def self.order_by_timestamp
    order("timestamp ASC")
  end

  def notify_real_time_feed
    ActionCable.server.broadcast(
      "real_time_events_channel", 
      event: event,
      email_type: email_type,
      timestamp: timestamp_string
    )
  end

  def timestamp_string
    timestamp.strftime("%d %b %Y - %H:%M:%S")
  end
end

app/models/event_builder.rb
class EventBuilder
  attr_reader :event_params

  def self.build(event_params:)
    new(event_params: event_params).build
  end

  def initialize(event_params:)
    @event_params = event_params
  end

  def build
    Event.new(event_attributes)
  end

  private

  def event_attributes
    {
      address: event_params["Address"],
      email_type: event_params["EmailType"],
      event: event_params["Event"],
      timestamp: unix_to_timestamp
    }
  end

  def unix_to_timestamp
    begin
      DateTime.strptime(event_params["Timestamp"].to_s,'%s')
    rescue
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    render locals: { data_miner: data_miner }
  end

  def create
    render :show, locals: { data_miner: data_miner }
  end

  private

  def dashboard_params
    params.permit(start_date: [:year, :month, :day], 
                  end_date: [:year, :month, :day])
  end

  def start_date_params
    dashboard_params.fetch(:start_date, nil)
  end

  def end_date_params
    dashboard_params.fetch(:end_date, nil)
  end

  def start_date
    if start_date_params
      Date.new(
        start_date_params[:year].to_i, 
        start_date_params[:month].to_i, 
        start_date_params[:day].to_i
      ).beginning_of_day
    else
      (Date.today - 7.days).beginning_of_day
    end
  end

  def end_date
    if end_date_params
      Date.new(
        end_date_params[:year].to_i, 
        end_date_params[:month].to_i, 
        end_date_params[:day].to_i
      ).end_of_day
    else
      Date.today.end_of_day
    end
  end

  def data_miner
    @_data_miner ||= DataMiner.new(
      start_date: start_date,
      end_date: end_date
    )
  end
end

app/controllers/data_requests_controller.rb
class DataRequestsController < ApplicationController

  def create
    DataRequest.new.save
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def create
    event = EventBuilder.build(event_params: event_params)
    if event.save
      head :ok
    else
      head :unprocessable_entity
    end
  end

  private

  def event_params
    params.permit("Address", "EmailType", "Event", "Timestamp")
  end

  def params
    ActionController::Parameters.new(JSON.parse(request.raw_post))
  end
end

app/controllers/real_time_events_controller.rb
class RealTimeEventsController < ApplicationController
  def show
    render locals: { data_miner: data_miner }
  end

  def data_miner
    @_data_miner ||= DataMiner.new(
      start_date: Date.today,
      end_date: Date.today
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/_rate_bar_chart.html.erb
<div class="chart-container">
  <div class="chart" id="chart">
    <div class="chart-header">
      <h5><%= type.underscore.humanize %></h5>
    </div>
    <div id='<%= "#{type}-bar-legend" %>' class="chart-legend"></div>
    <canvas height="300px" id='<%= "#{type}Chart" %>'></canvas><br>
  </div>
</div>

<script>
var <%= type %>Options = {
  responsive: true,
  scaleShowLabels : true,
  scaleOverride: true,
  scaleSteps: 10,
  scaleStepWidth: 10,
  legend: {
    display: true,
    labels: {
      fontColor: 'rgb(255, 99, 132)'
    }
  },
  scales: {
    xAxes: [{
      stacked: true
    }],
    yAxes: [{
      stacked: true
    }]
  }
};

//bar
var <%= type %>Data = {
  labels: ['<%= type.underscore.humanize %>'],
  datasets: [
  {
    label: 'Open rate',
    fillColor: "#028090",
    strokeColor: "#028090",
    borderWidth: 1,
    highlightFill: "#028090",
    highlightStroke: "#028090",
    data: [<%= "#{data_miner.open_rate(type: type)}" %>]
  },
  {
    label: 'Click rate',
    fillColor: "#69DDFF",
    strokeColor: "#69DDFF",
    borderWidth: 1,
    highlightFill: "#69DDFF",
    highlightStroke: "#69DDFF",
    data: [<%= "#{data_miner.click_rate(type: type)}" %>]
  }
  ]
};

$(document).ready( function() {
  var <%= "ctx#{type}" %> = document.getElementById('<%= "#{type}Chart" %>').getContext("2d");
  var <%= "#{type}Chart" %> = new Chart(<%= "ctx#{type}" %>).Bar(<%= type %>Data,<%= type %>Options);

  document.getElementById('<%= "#{type}-bar-legend" %>').innerHTML = <%= "#{type}Chart" %>.generateLegend();
});
</script>

app/views/dashboards/show.html.erb
<header>
  <div class="dashboard-details">
    <h1>Event Dashboard</h1>
    <%= form_tag dashboard_path do %>
      <p><%= label_tag :start_date %>
    <%= select_date Date.today - 7.days, order: [:day, :month, :year], prefix: :start_date %></br>
      <%= label_tag :end_date %>
    <%= select_date Date.today, order: [:day, :month, :year], prefix: :end_date %></p>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</header>
<section class="overall-stats content-block">
    <div class="dashboard-headline-stat-box">
      <div class="emails-sent">
        Emails sent: <%= data_miner.sent %></p>
      </div>
    </div>
    <div class="dashboard-headline-stat-box">
      <div class= "emails-opened">
        <p>Emails opened: <%= data_miner.opened %></p>
      </div>
    </div>
    <div class="dashboard-headline-stat-box">
      <div class="emails-clicked">
        <p>Total clicks: <%= data_miner.clicked %></p>
      </div>
    </div>
</section>
<section class="rate-stats content-block">
  <div>
    <h2>Open and click rate by email type</br>
      <small>Open rate is the percentage of emails sent that are opened, click rate is
        the percentage of emails sent that are clicked</small></h2>
  </div>
  <% if data_miner.show_conversion_rates? %>
    <% data_miner.all_email_types.each do |type| %>
      <%= render partial: "rate_bar_chart", locals: {type: type, data_miner: data_miner } %>
    <% end %>
  <% else %>
    <div class="no-charts">
    <h3>
      No emails have been sent. Send some in order to see conversion rates.
    </h3>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mandrilled</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section>
      <nav style="width:100%">
        <h1><%= link_to "Mandrilled", root_path, class: "home" %>
        <small>What do you need to know?</small></h1>
        <%= link_to "Real time events", real_time_events_path, class: "green-button" %>
      </nav>
    </section>

    <%= yield %>
  </body>
</html>

app/views/real_time_events/show.html.erb
<header>
  <div class="dashboard-details">
    <h1>Real Time Events</h1>
  </div>
</header>
<section class="real-time-stats content-block">
  <div class="toggle-real-time">
    <p><%= button_to "Request dummy data", data_request_path, remote: true, class: "orange-button" %></br>
  </div>
  <div class="real-time-events">
    <h3>Real time events </h3>
    <table class="table">
      <thead>
        <tr>
          <th>Event</th>
          <th>Email type</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        <% data_miner.last_ten_events.each do |event| %>
          <tr>
            <td><%= event.event %></td>
            <td><%= event.email_type %></td>
            <td><%= event.timestamp_string %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>